version: "3.9"

services:
  db:
    image: postgres:16
    container_name: boletin_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: miboletin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: boletin_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: miboletin
      DB_USER: postgres
      DB_PASSWORD: 123456
    depends_on:
      - db
volumes:
  postgres_data: